### PR TITLE
Add paging to LdapRepository

### PR DESCRIPTION
**Pull request by houcheng**
This commit adds paging query feature to data LDAP. The following two functions are added into LdapRepository interface:

```
	Page<T> findAll(Pageable pageable);
	Page<T> findAll(LdapQuery ldapQuery, Pageable pageable);
```

The paging query can be easily performed by the following code:
```

    Page<UnitTestPerson> pagedResult = tested.findAll(PageRequest.of(0, 50));
    while(true) {
        processData(pagedResult.getContent());

        if(pagedResult.hasNext()) {
            pagedResult = tested.findAll(pagedResult.nextPageable());
        } else {
            break;
        }
    }
```

### CODE REVIEW

**Comment by houcheng** [comment]
Hi @mp911de 

The PR is blocked by building error. The building for springldap-next profile was failed with the error message:

`[ERROR] Failed to execute goal on project spring-data-ldap: Could not resolve dependencies for project org.springframework.data:spring-data-ldap:jar:2.0.0.BUILD-SNAPSHOT: Failure to find org.springframework.ldap:spring-ldap-core:jar:2.4.0.BUILD-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-snapshots has elapsed or updates are forced -> [Help 1]`


Please look at this and thank you.
Houcheng

/cc @rwinch

**Comment by mp911de** [comment]
Thanks for your PR. I will take it from here.

**Comment by mp911de** [comment]
I adapted your code at https://github.com/spring-projects/spring-data-ldap/tree/issue/DATALDAP-30 and introduced sliced query execution for repository query methods.

**Comment by houcheng** [comment]
Thank you.

**Comment by mp911de** [comment]
Closing this pull request without merge as per comments in https://jira.spring.io/browse/DATALDAP-30. Thank you for your effort for this pull request.

**Pull request closed without merging**
